language: bash
sudo: required
services: docker
env:
  global:
    - DOCKER_REPO=rocketbaseio/pdfmaker
    - COMMIT=${TRAVIS_COMMIT::8}
    -
deploy:
  script: '
  docker login -u $DOCKER_USER -p $DOCKER_PASS &&
  docker buildx build \
    --platform linux/amd64,linux/arm64,linux/arm/v7 \
    -t "$DOCKER_REPO:multi-arch" \
    --push \
    .'
  on:
    branch: master
    tags: true

notifications:
  email: true
