version: '3.5'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: pdfmaker-reworked/server:latest
    ports:
      - "8081:8081"

